version: "2"

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - misspell
    - nakedret
    - goheader
    - bodyclose
    - contextcheck
    - durationcheck
    - gocritic
    - prealloc
    - sqlclosecheck
    - unconvert
    - unparam
    - predeclared
    - gosec

formatters: 
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
